[phases.setup]
nixPkgs = ['python310Full', 'nodejs_18', 'pnpm-9_x']

providers = ["node"]

[phases.install]
cmds = ["npm install -g corepack", "corepack enable", "corepack prepare pnpm@9.1.0 --activate", "pnpm install"]
