/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import i18N from "@strapi/plugin-i18n/strapi-admin";
import openAi from "@strapi/plugin-open-ai/strapi-admin";
import documentation from "@strapi/plugin-documentation/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import importExportEntries from "strapi-plugin-import-export-entries/strapi-admin";
import meilisearch from "strapi-plugin-meilisearch/strapi-admin";
import restCache from "strapi-plugin-rest-cache/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    i18n: i18N,
    "open-ai": openAi,
    documentation: documentation,
    "users-permissions": usersPermissions,
    "import-export-entries": importExportEntries,
    meilisearch: meilisearch,
    "rest-cache": restCache,
  },
});
